# Generated by Django 5.2.4 on 2026-10-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("helloAssoImporter", "0006_member_formations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Thème de la séance (facultatif)",
                        max_length=200,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Déroulé / remarques (visibles par l'équipe encadrante uniquement)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cursus",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Niveaux préparés pendant la séance",
                        related_name="training_sessions",
                        to="helloAssoImporter.cursus",
                    ),
                ),
                (
                    "instructors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="training_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_sessions",
                        to="helloAssoImporter.season",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séance",
                "verbose_name_plural": "Séances",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="StudentNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("content", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("staff", "Équipe encadrante uniquement"),
                            ("student", "Visible par l'élève"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_notes",
                        to="helloAssoImporter.member",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_notes",
                        to="suivi.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note élève",
                "verbose_name_plural": "Notes élèves",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=200)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("not_done", "À refaire"),
                            ("partial", "Partiellement réussi"),
                            ("success", "Réussi"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="helloAssoImporter.member",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="helloAssoImporter.skill",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="suivi.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice",
                "verbose_name_plural": "Exercices",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("excused", "Absent excusé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="helloAssoImporter.member",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="suivi.trainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence",
                "verbose_name_plural": "Présences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "member"), name="unique_session_attendance"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkedSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("not_acquired", "Non acquis"),
                            ("in_progress", "En cours d'acquisition"),
                            ("acquired", "Acquis"),
                        ],
                        help_text="Évaluation lors de la séance (vide = travaillée sans évaluation)",
                        max_length=20,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worked_skills",
                        to="helloAssoImporter.member",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worked_skills",
                        to="suivi.trainingsession",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worked_skills",
                        to="helloAssoImporter.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence travaillée",
                "verbose_name_plural": "Compétences travaillées",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "member", "skill"),
                        name="unique_worked_skill",
                    )
                ],
            },
        ),
    ]
